<?php

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php
if ($block->getItem()->getPrice()!='0' || $block->getItem()->getPrice()!='0.0000'):
    if ($block->isProductVisibleInSiteVisibility()):?>
    <a class="action action-edit"
       href="<?= $block->escapeUrl($block->getConfigureUrl()) ?>"
       title="<?= $block->escapeHtmlAttr(__('Edit item parameters')) ?>">
        <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
    <?php endif ?>
<?php endif ?>
